export interface IAuthModel {
    user: string,
    token: string,
    customer_profile_name: string,
    loggedInAt: string,
    usertype: string,
    customer_id: string,
    customer_name: string,
    contact_no: string,
    email: string,
    risk_profile: string,
    risk_rating: string,
    last_KYC_Done_On: string,
    next_KYC_Due_On: string,
    onboardStartDate: string,
    account_currency: string,
    cif: string,
    account_number: string,
    account_type: string,
};